### ISSUE TITLE
Configuration management

### ISSUE THREAD

**Issue by styts** [phaidra/phaidra-ui#14]
_Draft. TBD on Thursday._

We have multiple instances, and need a way to manage their configurations.

## Instances
- e-book.fwf.ac.at [angular]
- phaidra.bibliothek.uni-ak.ac.at [old perl? thing]
- phaidra.cab.unipd.it [custom, angular-material, jquery]
- phaidra.fhstp.ac.at [old perl? thing]
- phaidra.kug.ac.at [angular]
- phaidra.ufg.at [old perl? thing]
- volare.vorarlberg.at [old perl? thing]

## There are essentially two ways:
A) decide on the configuration at build time, baking it in with the build.
- requires building the software anew for each instance
- others' configs are not visible

B) ship all configurations with the build, pick the right one based on the value
of `location.host` (env "sniffing").
- one build for all
- everyone's configs are visible to all parties (open source)

## Switching at runtime
Do we want to be able to switch configs at runtime? It seems like we do (e.g.
using the header dropdown on app01), at least on non-production instances (to
test styles, etc.).

## Privacy
Are we (and other unis) comfortable having the configuration options saved in a open source repository?
It's not a problem to have private configs outside the repo.
They should still be able to make build with `INSTANCE=foo`, that would target their private config.

## What's part of an instance config?
- api urls
- theme settings
- search facets
- logo url
- language (#11)

(which of these should be changeable dynamically?)

## Search
Is a route target component, so passing props to it (dynamic ones) is not possible.

## Settings Store
I think the vuex store is a perfectly adequate place for keeping the settings.
Comonents can react when accessing the settigns as they do now.
Alternatively we can use global 'settings' mixin as discussed before.

## Solution
Best of both worlds.
Do separate builds per instance, bundling only the required config.
Config can keep the current style, with global settings, and switchable settings.
Use a tool like webpack's https://webpack.js.org/plugins/normal-module-replacement-plugin/
to make importing a config file be resolved based on an env var.
Build can then be called with `INSTANCE=univie npm run build`: webpack will
include `config/univie.js` when you write `import config from 'APP_CONFIG'`
App.vue will then place the config into the store, under settings, as it does now.
When these settings change, components like search can update reactively.
This means we will have no symlinks.

**Comment by RastislavHudak** [comment]
config is now generated by phaidra-core, so links seems a more reasonable option
