### ISSUE TITLE
Object versions in search results

### ISSUE THREAD

**Issue by giulioturetta** [phaidra/phaidra-ui#19]
- remove -hassuccessor:* when searching for collection members otherwise objects whose version isn't the latest won't be displayed in search results

- Show a label like "This object has a later version" in search results when an object has a later version. That could also be a link to the successor.

**Comment by giulioturetta** [comment]
It was deemed that versions of an object other than the most recent won't be displayed in search results as they can just create noise.

A warning message should be displayed on the landing page of an object which has a later version. Example wording may be similar to "There is a more recent version of this object available." with a link to the successor object (cf. http://researchdata.cab.unipd.it/112/).

**Comment by RastislavHudak** [comment]
done
