### ISSUE TITLE
EXIF metadata

### ISSUE THREAD

**Issue by giulioturetta** [phaidra/phaidra-ui#23]
Show EXIF metadata on detail object page?

Consider generating EXIF metadata on the fly upon user's request instead of ingesting it as a datastream. Any authorization needed? Caching needed?

**Comment by RastislavHudak** [comment]
I don't think this feature is used much and users are probably not even aware that the exif metadata are available like this and what they possibly contain. As with other embedded metadata these are often either uninteresting technical details if generated automatically, or quite likely false if set (and not consistently updated) manually. Whoever wants to see them can always download the picture and extract it anyway, so I'd skip this feature for now.
