### ISSUE TITLE
Meta tags for social media

### ISSUE THREAD

**Issue by giulioturetta** [phaidra/phaidra-ui#33]
Consider adding [Open Graph](https://developers.facebook.com/docs/sharing/webmasters/) and [Twitter Card](https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/getting-started) meta tags for better sharing of Phaidra webpages on social media.

Useful reference (albeit a bit old): https://css-tricks.com/essential-meta-tags-social-media/

HTML metadata manager for Vue.js: https://vue-meta.nuxtjs.org/

**Comment by csandeepkumarfl2023** [comment]
reference PR: https://github.com/phaidra/phaidra-ui/pull/46

**Comment by giulioturetta** [comment]
Might be worth checking if changing "name" to "property" in https://github.com/phaidra/phaidra-ui/blob/master/pages/detail/_pid.vue#L2495 makes Open Graph and TwitterCard metadata work.
