### ISSUE TITLE
add csv export to search

### ISSUE THREAD

**Issue by RastislavHudak** [phaidra/phaidra-ui#45]
see eg https://github.com/phaidra/theke/blob/a4ca5fe9a6b373232bfb95e24717865673d5a922/src/components/Search.vue#L208

only add 'pid', 'dc_title', 'dc_creator' and 'bib_published' for now.

**Comment by csandeepkumarfl2023** [comment]
reference PR: https://github.com/phaidra/phaidra-vue-components/pull/38
